### ISSUE TITLE
Implement JSON event serialization using org.apache.kafka.common.serialization.Serializer?

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-event-serialization#1]
It would be nice if events were serialized as JSON and not as String byte[].  Using Camel, I have understood how events can be unmarshalled and the fields can be read.  However, with Druid it seems that a normal downstream KafkaConsumer expects a Kafka payload to be "ready to read" (probably for performance reasons).  Is it possible to implement KafkaSerializer methods in EventSerializer and use it instead of StringSerializer with Producer?

**Comment by ajs6f** [comment]
What is a `String byte[]`?

**Comment by christopher-johnson** [comment]
https://kafka.apache.org/090/javadoc/org/apache/kafka/common/serialization/StringSerializer.html
A String that is serialized as a byte[]

**Comment by ajs6f** [comment]
For those of us who won't be using Kafka, a Kafka-specific serialization would be a barrier to use.

**Comment by acoburn** [comment]
I'd prefer to keep this module independent of any particular transport technology, whether that is Kafka, JMS, WebSockets, etc. Otherwise, you end up with all sorts of dependency chains that are counter-productive in the long term. As it is, this class will serialize an event as a `String`, which is readable as "regular" JSON or as JSON-LD. This also makes reading the data with non-JVM clients much easier, since the bytes are readable as simple UTF-8.

Plus, I am already serializing everything in Kafka with the StringSerializer (this is defined in the `trellis-app` layer: https://github.com/trellis-ldp/trellis-app/blob/master/src/main/java/org/trellisldp/app/TrellisUtils.java#L90-L91)

**Comment by acoburn** [comment]
@ajs6f as a little background, Kafka stores all data internally as a byte array, but when producers or consumers are instantiated, you do so with an appropriate Serializer or Deserializer class. That way, when the client reads the message, it has already been converted from the internal byte array into a Java Object.

When I initially wrote the Kafka layer in the Trellis implementation code, I had a `Datastream` serializer, but I found that it was just a lot easier to just use a `String` to represent the data flow. One could argue that a binary format would be more efficient, but I see no need to optimize that at present.

**Comment by acoburn** [comment]
And just to add a further point, which @ajs6f already hinted at -- not every implementation of the Trellis API will use Kafka. One of the important things about Trellis' JAVA API is that it does not impose many dependencies on a potential implementer. And likewise, for the particular modules that implement parts of the API, you want to be very careful about what dependencies are added.

**Comment by christopher-johnson** [comment]
OK, makes sense.  

If I understand you correctly, there should be no reason why the downstream object mapper cannot read the event, since it is definitely a JSON object, even though it was serialized using the StringSerializer.

An alternative serializer like [this one](https://github.com/confluentinc/schema-registry/blob/master/json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonSerializer.java) would need to go in trellis-kafka, I guess because it depends on kafka.  

Anyway, I have done a bit more digging into my issue, and I guess that it does not have to do with the payload itself, but with the way that I have defined the metric schema for a non-countable field. 
Here is the error for reference:
```bash
2017-11-05T15:01:54,671 ERROR [MonitorScheduler-0] io.druid.segment.realtime.RealtimeMetricsMonitor - [10] Unparseable events! Turn on debug logging to see exception stack trace.```

Druid is quite difficult, but intriguing.  I have made it compute offsets and it reads the event stream, but I cannot persist the events yet.  I will keep working on it.  I will close this issue.  Thank you for the input.

**Comment by acoburn** [comment]
Actually, you wouldn't need to make any changes to trellis-kafka.

You will see that the constructor accepts a [`KafkaProducer<String, String>`](https://github.com/trellis-ldp/trellis-kafka/blob/master/src/main/java/org/trellisldp/kafka/KafkaPublisher.java#L49): 

When that object is created in a downstream application, the appropriate String serializer will have already been registered (so you could use such an alternate serializer at that point, if you wish).
