### ISSUE TITLE
include "published" property in ActivityStreamMessage?

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-event-serialization#2]
Do you see an issue with adding "[published](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-published)" in the ActivityStreamMessage? 
 
I have understood today that the problem I am having with Druid is that it requires a timestampSpec in the event message since it does not depend on Kafka metadata.  I am able to persist messages if I manually set a timestamp.
  
One of the concerns that I am attempting to resolve with my use case is how to trigger "batch process" downstream serialization using ActivityStreamMessages generated from repository events.   For example, I have an ingest process A that may run from time t1 to time t2 followed by another B that runs from time t3 to time t4.  I may have different specs for A and B, so I need a way to identify and get the creation events that apply to a certain collection process.  While I probably could manually filter them by resource identifier, it seems consistent with OLAP (generally) to partition by timeseries.  

Also, I can get the production process init time easier than I can get a resource identifier, since it is not embedded in the data.

**Comment by acoburn** [comment]
I have no objections whatsoever. Feel free to make a PR to add that field.

You should be able to simply get that value from `Event::getCreated`.

**Comment by ajs6f** [comment]
I don't see a problem with a timestamp, as long as the semantics of that data are _very_ clearly defined. Especially in a distributed environment, we have to distinguish between "time a mutation occurred" and "time an event was emitted". It's the latter you want to include, right?

**Comment by acoburn** [comment]
Yes, what @ajs6f said.

It is perhaps worth noting that the `Event::getCreated` value refers to when the _event_ was created; it has nothing to do with when the resource was created/modified/deleted (though in a practical sense, the value will be pretty close to the resource creation/modification date - you just cannot rely on those two values being close or even the same)

**Comment by christopher-johnson** [comment]
right, and the correspondence to a specific resource is established in the event body itself.  I would not run a query for resources by modification time. Rather by events between times + resource criteria (as required).  I will do a PR for this.  Thanks for the help.

**Comment by ajs6f** [comment]
👍
